---
- name: Hello world
  hosts: all
  vars:
    something: world

  tasks:
    - name: Show templating results
      ansible.builtin.debug:
        msg: "{{ lookup('template', './some_template.j2') }}"
